server:
  port: 7001

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:7002/
          predicates:
            - Path=/users/**
        - id: login
          uri: http://localhost:7002/login
          predicates:
            - Path=/login
        - id: product
          uri: http://localhost:7000/
          predicates:
            - Path=/products/**